import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Congratulations!</h1>
    <div>
      <p>You've completed the essentials of automated application deployment with GitHub Actions! 🥳</p>
      <div style="width:100%;height:0;padding-bottom:75%;position:relative;"><iframe src="https://giphy.com/embed/W2oHQI3Y8Vu7IcI6k1" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/bosch-power-tools-electric-W2oHQI3Y8Vu7IcI6k1">via GIPHY</a></p>
  </div>

  <iframe src="https://giphy.com/embed/W2oHQI3Y8Vu7IcI6k1" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/bosch-power-tools-electric-W2oHQI3Y8Vu7IcI6k1">via GIPHY</a></p>
      </main>
    </>
  )
}
